include:
  - node_ident/hermi01
  - node_ident/hermi02
  - node_ident/mero02
  - node_ident/mero06
  - node_ident/mero08
  - node_ident/mero10
  - node_ident/mero07
  - node_ident/mero09
  - node_ident/mero04
  - node_ident/mero05
